---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: influxdb
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      nodePort: 30086
